import bcrypt from "bcryptjs";
import { dbStore } from "../config/db.ts";
import {
  IUser,
  ILawyerProfile,
  IConsultationRequest,
  ICase,
  IDocument,
} from "../models/types.ts";

export const LEGAL_CATEGORIES = [
  {
    id: "property-law",
    name: "Property Law",
    description: "Property disputes, tenancy agreements, landlord obligations, and real estate ownership.",
    icon: "Building",
  },
  {
    id: "divorce-family",
    name: "Divorce & Family Law",
    description: "Divorce, child custody, alimony, separation agreements, and domestic relations.",
    icon: "HeartHandshake",
  },
  {
    id: "criminal-law",
    name: "Criminal Law",
    description: "Defense against criminal charges, trials, bail hearings, investigations, and appeals.",
    icon: "ShieldAlert",
  },
  {
    id: "civil-law",
    name: "Civil Law",
    description: "Contract disputes, torts, personal liability, negligence, and private rights enforcement.",
    icon: "Scale",
  },
  {
    id: "corporate-business",
    name: "Corporate & Business Law",
    description: "Entity formation, commercial contracts, M&A, regulatory compliance, and governance.",
    icon: "Briefcase",
  },
  {
    id: "employment-labour",
    name: "Employment & Labour Law",
    description: "Wrongful termination, workplace harassment, wage claims, and severance negotiations.",
    icon: "Users",
  },
  {
    id: "consumer-law",
    name: "Consumer Law",
    description: "Defective products, fraudulent advertising, consumer rights protection, and unfair terms.",
    icon: "ShoppingBag",
  },
  {
    id: "cyber-law",
    name: "Cyber Law",
    description: "Data privacy, cyber fraud, unauthorized access, identity theft, and digital disputes.",
    icon: "Laptop",
  },
  {
    id: "tax-law",
    name: "Tax Law",
    description: "Income tax disputes, IRS audits, tax compliance, cross-border structuring, and appeals.",
    icon: "Receipt",
  },
  {
    id: "intellectual-property",
    name: "Intellectual Property",
    description: "Patents, trademarks, copyright infringement, licensing, and trade secret protection.",
    icon: "Lightbulb",
  },
  {
    id: "immigration-law",
    name: "Immigration Law",
    description: "Work visas, permanent residency, asylum, citizenship applications, and deportation defense.",
    icon: "Globe",
  },
  {
    id: "banking-finance",
    name: "Banking & Finance",
    description: "Loan defaults, debt restructuring, financial fraud, regulatory compliance, and securities.",
    icon: "Landmark",
  },
  {
    id: "accident-claims",
    name: "Motor Vehicle / Accident Claims",
    description: "Traffic collisions, vehicle damage recovery, personal injury compensation, and insurance claims.",
    icon: "Car",
  },
  {
    id: "real-estate",
    name: "Real Estate Law",
    description: "Title verification, property acquisitions, zoning regulations, leasing, and land disputes.",
    icon: "Home",
  },
];

export async function seedDatabaseIfEmpty(): Promise<void> {
  await dbStore.load();
  const currentData = dbStore.getData();

  // If already seeded with users, keep data
  if (currentData.users && currentData.users.length >= 20) {
    return;
  }

  console.log("Seeding LegalConnect with comprehensive demo data...");

  const defaultPasswordHash = bcrypt.hashSync("password123", 10);
  const adminPasswordHash = bcrypt.hashSync("admin123", 10);
  const lawyerPasswordHash = bcrypt.hashSync("lawyer123", 10);

  // 1. Admin User
  const adminUser: IUser = {
    _id: "usr_admin_01",
    name: "LegalConnect Admin",
    email: "admin@legalconnect.com",
    phone: "+1 (555) 010-0001",
    password: adminPasswordHash,
    role: "admin",
    status: "active",
    createdAt: new Date("2026-01-01").toISOString(),
  };

  // 2. Five Demo Clients
  const clientUsers: IUser[] = [
    {
      _id: "usr_client_01",
      name: "Sarah Jenkins",
      email: "sarah@demo.legalconnect.com",
      phone: "+1 (555) 021-1001",
      password: defaultPasswordHash,
      role: "client",
      status: "active",
      createdAt: new Date("2026-01-10").toISOString(),
    },
    {
      _id: "usr_client_02",
      name: "Michael Chen",
      email: "michael@demo.legalconnect.com",
      phone: "+1 (555) 021-1002",
      password: defaultPasswordHash,
      role: "client",
      status: "active",
      createdAt: new Date("2026-01-15").toISOString(),
    },
    {
      _id: "usr_client_03",
      name: "Emily Rodriguez",
      email: "emily@demo.legalconnect.com",
      phone: "+1 (555) 021-1003",
      password: defaultPasswordHash,
      role: "client",
      status: "active",
      createdAt: new Date("2026-02-01").toISOString(),
    },
    {
      _id: "usr_client_04",
      name: "David Kumar",
      email: "david@demo.legalconnect.com",
      phone: "+1 (555) 021-1004",
      password: defaultPasswordHash,
      role: "client",
      status: "active",
      createdAt: new Date("2026-02-12").toISOString(),
    },
    {
      _id: "usr_client_05",
      name: "Lisa Watson",
      email: "lisa@demo.legalconnect.com",
      phone: "+1 (555) 021-1005",
      password: defaultPasswordHash,
      role: "client",
      status: "active",
      createdAt: new Date("2026-03-01").toISOString(),
    },
  ];

  // 3. 20 Demo Lawyers with user accounts & lawyer profiles
  const demoLawyerRaw = [
    {
      id: "lawyer_01",
      name: "Adv. Marcus Vance",
      email: "marcus.vance@demo.legalconnect.com",
      phone: "+1 (555) 301-1001",
      specialization: "Tenancy & Landlord-Tenant Disputes",
      categories: ["Property Law", "Real Estate Law", "Civil Law"],
      experience: 14,
      location: "New York, NY",
      languages: ["English", "Spanish"],
      education: "J.D., Columbia Law School",
      bio: "Adv. Vance is an experienced civil litigator dedicated to residential and commercial tenancy disputes, lease negotiations, and security deposit recovery.",
      fee: 150,
      modes: ["Video Call", "Phone Call", "In-Person"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 09:00 - 16:00", "Saturday 10:00 - 13:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_02",
      name: "Adv. Elena Rostova",
      email: "elena.rostova@demo.legalconnect.com",
      phone: "+1 (555) 301-1002",
      specialization: "Corporate Contracts & Entity Formation",
      categories: ["Corporate & Business Law", "Tax Law", "Intellectual Property"],
      experience: 18,
      location: "San Francisco, CA",
      languages: ["English", "Russian", "French"],
      education: "LL.M., Stanford Law School",
      bio: "Advising early-stage startups and enterprises on incorporation, venture terms, partnership disputes, and cross-border commercial transactions.",
      fee: 250,
      modes: ["Video Call", "Phone Call"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Tue-Thu 10:00 - 17:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_03",
      name: "Adv. Priya Patel",
      email: "priya.patel@demo.legalconnect.com",
      phone: "+1 (555) 301-1003",
      specialization: "Divorce, Custody & Marital Settlement",
      categories: ["Divorce & Family Law", "Civil Law"],
      experience: 11,
      location: "Chicago, IL",
      languages: ["English", "Hindi", "Gujarati"],
      education: "J.D., Northwestern Pritzker School of Law",
      bio: "Focuses on compassionate family mediation, child custody arrangements, spousal maintenance, and asset distribution.",
      fee: 175,
      modes: ["Video Call", "Phone Call", "In-Person"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Wed 09:00 - 15:00", "Friday 10:00 - 14:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_04",
      name: "Adv. Jonathan Reed",
      email: "jonathan.reed@demo.legalconnect.com",
      phone: "+1 (555) 301-1004",
      specialization: "Criminal Defense & Trial Advocacy",
      categories: ["Criminal Law", "Civil Law"],
      experience: 22,
      location: "Los Angeles, CA",
      languages: ["English"],
      education: "J.D., UCLA School of Law",
      bio: "Former prosecutor offering criminal defense representation for misdemeanors, felonies, state court hearings, and appeals.",
      fee: 280,
      modes: ["Video Call", "In-Person"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 08:30 - 18:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_05",
      name: "Adv. Aisha Morales",
      email: "aisha.morales@demo.legalconnect.com",
      phone: "+1 (555) 301-1005",
      specialization: "Workplace Discrimination & Wage Recovery",
      categories: ["Employment & Labour Law", "Civil Law"],
      experience: 9,
      location: "Austin, TX",
      languages: ["English", "Spanish"],
      education: "J.D., University of Texas School of Law",
      bio: "Defends employees in unlawful termination claims, wage and overtime discrepancies, non-compete clauses, and workplace harassment.",
      fee: 140,
      modes: ["Video Call", "Phone Call"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 10:00 - 17:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_06",
      name: "Adv. Raymond Sterling",
      email: "raymond.sterling@demo.legalconnect.com",
      phone: "+1 (555) 301-1006",
      specialization: "Cybercrime, Data Privacy & Online Fraud",
      categories: ["Cyber Law", "Consumer Law", "Intellectual Property"],
      experience: 12,
      location: "Seattle, WA",
      languages: ["English", "German"],
      education: "J.D. / M.S. Cybersecurity, University of Washington",
      bio: "Assisting victims of identity theft, crypto fraud, unauthorized access, and advising digital businesses on GDPR and state privacy compliance.",
      fee: 210,
      modes: ["Video Call", "Phone Call"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 09:00 - 17:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_07",
      name: "Adv. Maya Lin",
      email: "maya.lin@demo.legalconnect.com",
      phone: "+1 (555) 301-1007",
      specialization: "Patent Prosecution & Trademark Protection",
      categories: ["Intellectual Property", "Corporate & Business Law"],
      experience: 15,
      location: "Boston, MA",
      languages: ["English", "Mandarin"],
      education: "J.D., Harvard Law School",
      bio: "Patent attorney specializing in biotech, software patents, trademark registration, and defense against IP infringement claims.",
      fee: 300,
      modes: ["Video Call", "Phone Call", "In-Person"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Thu 10:00 - 16:30"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_08",
      name: "Adv. Tariq Al-Mansoor",
      email: "tariq.almansoor@demo.legalconnect.com",
      phone: "+1 (555) 301-1008",
      specialization: "Immigration Visas & Naturalization",
      categories: ["Immigration Law", "Civil Law"],
      experience: 10,
      location: "Miami, FL",
      languages: ["English", "Arabic", "Spanish"],
      education: "J.D., Georgetown University Law Center",
      bio: "Navigating family petitions, employment-based green cards (EB-1/EB-2), citizenship proceedings, and consular appeals.",
      fee: 160,
      modes: ["Video Call", "Phone Call", "In-Person"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 09:30 - 17:30"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_09",
      name: "Adv. Claire Beaumont",
      email: "claire.beaumont@demo.legalconnect.com",
      phone: "+1 (555) 301-1009",
      specialization: "Automobile Collisions & Bodily Injury Claims",
      categories: ["Motor Vehicle / Accident Claims", "Civil Law"],
      experience: 16,
      location: "Atlanta, GA",
      languages: ["English", "French"],
      education: "J.D., Emory University School of Law",
      bio: "Advocating for victims of multi-vehicle accidents, distracted driving collisions, pedestrian accidents, and insurance bad faith.",
      fee: 130,
      modes: ["Video Call", "Phone Call", "In-Person"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 08:00 - 18:00", "Saturday 09:00 - 12:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_10",
      name: "Adv. Arthur Pendelton",
      email: "arthur.pendelton@demo.legalconnect.com",
      phone: "+1 (555) 301-1010",
      specialization: "IRS Audits & Federal Tax Resolution",
      categories: ["Tax Law", "Corporate & Business Law", "Banking & Finance"],
      experience: 24,
      location: "Washington, DC",
      languages: ["English"],
      education: "LL.M. in Taxation, NYU School of Law",
      bio: "Representing high-net-worth individuals and corporations in federal tax controversy, IRS audits, payroll tax penalties, and tax court litigation.",
      fee: 320,
      modes: ["Video Call", "Phone Call"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Thu 09:00 - 15:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_11",
      name: "Adv. Sofia Rossi",
      email: "sofia.rossi@demo.legalconnect.com",
      phone: "+1 (555) 301-1011",
      specialization: "Consumer Protection & False Advertising",
      categories: ["Consumer Law", "Civil Law"],
      experience: 8,
      location: "Denver, CO",
      languages: ["English", "Italian"],
      education: "J.D., University of Colorado Law",
      bio: "Guiding consumers through deceptive trade practices, warranties, lemon law claims, and predatory lending disputes.",
      fee: 110,
      modes: ["Video Call", "Phone Call"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 10:00 - 16:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_12",
      name: "Adv. Liam Gallagher",
      email: "liam.gallagher@demo.legalconnect.com",
      phone: "+1 (555) 301-1012",
      specialization: "Real Estate Title Examination & Zoning",
      categories: ["Real Estate Law", "Property Law"],
      experience: 13,
      location: "Philadelphia, PA",
      languages: ["English"],
      education: "J.D., Penn Carey Law",
      bio: "Assisting property buyers and developers with land use permits, zoning variances, clear title actions, and boundary disputes.",
      fee: 190,
      modes: ["Video Call", "In-Person"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 09:00 - 16:30"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_13",
      name: "Adv. Meera Nair",
      email: "meera.nair@demo.legalconnect.com",
      phone: "+1 (555) 301-1013",
      specialization: "Banking Compliance & Debt Dispute Resolution",
      categories: ["Banking & Finance", "Consumer Law"],
      experience: 11,
      location: "Charlotte, NC",
      languages: ["English", "Malayalam", "Hindi"],
      education: "J.D., Duke University School of Law",
      bio: "Consulting on consumer credit disputes, mortgage modifications, creditor harassment, and loan default workouts.",
      fee: 165,
      modes: ["Video Call", "Phone Call"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 09:00 - 17:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_14",
      name: "Adv. Carlos Mendoza",
      email: "carlos.mendoza@demo.legalconnect.com",
      phone: "+1 (555) 301-1014",
      specialization: "Civil Litigation & Breach of Contract",
      categories: ["Civil Law", "Property Law"],
      experience: 17,
      location: "Phoenix, AZ",
      languages: ["English", "Spanish"],
      education: "J.D., Sandra Day O'Connor College of Law",
      bio: "Trial attorney handling complex breach of contract disputes, civil fraud, partnership dissolution, and property damage actions.",
      fee: 220,
      modes: ["Video Call", "Phone Call", "In-Person"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 08:30 - 17:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_15",
      name: "Adv. Hannah Gross",
      email: "hannah.gross@demo.legalconnect.com",
      phone: "+1 (555) 301-1015",
      specialization: "Domestic Relations & Adoption Law",
      categories: ["Divorce & Family Law"],
      experience: 7,
      location: "Portland, OR",
      languages: ["English", "German"],
      education: "J.D., Lewis & Clark Law School",
      bio: "Focused on domestic legal matters, legal adoption, foster guardianship, post-nuptial agreements, and amicable divorce resolution.",
      fee: 125,
      modes: ["Video Call", "Phone Call"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Thu 09:00 - 15:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_16",
      name: "Adv. Kenneth O'Connor",
      email: "kenneth.oconnor@demo.legalconnect.com",
      phone: "+1 (555) 301-1016",
      specialization: "DUI Defense & Traffic Violations",
      categories: ["Criminal Law", "Motor Vehicle / Accident Claims"],
      experience: 14,
      location: "Dallas, TX",
      languages: ["English"],
      education: "J.D., SMU Dedman School of Law",
      bio: "Defending motorists facing reckless driving charges, DUI citations, license revocations, and administrative traffic hearings.",
      fee: 180,
      modes: ["Video Call", "Phone Call", "In-Person"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Sat 09:00 - 18:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_17",
      name: "Adv. Nadia Farooq",
      email: "nadia.farooq@demo.legalconnect.com",
      phone: "+1 (555) 301-1017",
      specialization: "Immigration Asylum & Deportation Defense",
      categories: ["Immigration Law", "Civil Law"],
      experience: 10,
      location: "Houston, TX",
      languages: ["English", "Urdu", "Arabic"],
      education: "J.D., University of Houston Law Center",
      bio: "Dedicated advocate for asylum seekers, humanitarian parole, cancellation of removal, and refugee adjustment of status.",
      fee: 145,
      modes: ["Video Call", "Phone Call", "In-Person"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 09:00 - 16:30"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_18",
      name: "Adv. Victor Novak",
      email: "victor.novak@demo.legalconnect.com",
      phone: "+1 (555) 301-1018",
      specialization: "Software Licensing & Trade Secrets",
      categories: ["Intellectual Property", "Cyber Law", "Corporate & Business Law"],
      experience: 19,
      location: "San Jose, CA",
      languages: ["English", "Polish"],
      education: "J.D., UC Berkeley School of Law",
      bio: "Drafting software licensing agreements, SaaS contracts, non-disclosure terms, and prosecuting intellectual property misappropriation.",
      fee: 290,
      modes: ["Video Call", "Phone Call"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Tue-Fri 10:00 - 17:00"],
      verification: "verified" as const,
    },
    {
      id: "lawyer_19",
      name: "Adv. Rachel Sterling",
      email: "rachel.sterling@demo.legalconnect.com",
      phone: "+1 (555) 301-1019",
      specialization: "Commercial Real Estate Leases & Land Purchase",
      categories: ["Real Estate Law", "Property Law", "Corporate & Business Law"],
      experience: 6,
      location: "Minneapolis, MN",
      languages: ["English"],
      education: "J.D., University of Minnesota Law School",
      bio: "Assisting small businesses with storefront leases, retail development agreements, and commercial purchase contracts.",
      fee: 135,
      modes: ["Video Call", "Phone Call"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 09:00 - 16:00"],
      verification: "pending" as const, // For admin approval demo
    },
    {
      id: "lawyer_20",
      name: "Adv. Benjamin Hayes",
      email: "benjamin.hayes@demo.legalconnect.com",
      phone: "+1 (555) 301-1020",
      specialization: "Severance Negotiation & Executive Compensation",
      categories: ["Employment & Labour Law", "Corporate & Business Law"],
      experience: 12,
      location: "San Diego, CA",
      languages: ["English", "Spanish"],
      education: "J.D., USD School of Law",
      bio: "Representing executives and employees in severance packaging, non-solicitation covenants, and compensation disputes.",
      fee: 215,
      modes: ["Video Call", "Phone Call"] as ("Video Call" | "Phone Call" | "In-Person")[],
      availability: ["Mon-Fri 10:00 - 18:00"],
      verification: "verified" as const,
    },
  ];

  const lawyerUsers: IUser[] = [];
  const lawyerProfiles: ILawyerProfile[] = [];

  demoLawyerRaw.forEach((dl) => {
    const userId = `usr_${dl.id}`;
    lawyerUsers.push({
      _id: userId,
      name: dl.name,
      email: dl.email,
      phone: dl.phone,
      password: lawyerPasswordHash,
      role: "lawyer",
      status: "active",
      createdAt: new Date("2026-01-05").toISOString(),
    });

    lawyerProfiles.push({
      _id: `prof_${dl.id}`,
      userId,
      name: dl.name,
      email: dl.email,
      phone: dl.phone,
      specialization: dl.specialization,
      categories: dl.categories,
      experience: dl.experience,
      location: dl.location,
      languages: dl.languages,
      education: dl.education,
      bio: dl.bio,
      consultationFee: dl.fee,
      consultationModes: dl.modes,
      availability: dl.availability,
      verificationStatus: dl.verification,
      avatarUrl: `https://api.dicebear.com/7.x/initials/svg?seed=${encodeURIComponent(
        dl.name
      )}&backgroundColor=0f172a,1e293b,334155`,
      isDemo: true,
      consultationCount: Math.floor(Math.random() * 20) + 12,
      createdAt: new Date("2026-01-05").toISOString(),
    });
  });

  // 4. Initial Consultation Requests
  const demoConsultations: IConsultationRequest[] = [
    {
      _id: "req_demo_01",
      clientId: "usr_client_01",
      clientName: "Sarah Jenkins",
      clientEmail: "sarah@demo.legalconnect.com",
      clientPhone: "+1 (555) 021-1001",
      lawyerId: "prof_lawyer_01",
      lawyerName: "Adv. Marcus Vance",
      category: "Property Law",
      problemDescription: "My landlord withheld my $2,400 security deposit citing normal wall scuffs that were present at move-in. I have photographic evidence from the move-in inspection.",
      preferredDate: "2026-09-28",
      preferredTime: "11:00 AM",
      mode: "Video Call",
      status: "Accepted",
      notes: "Please have your lease agreement and inspection checklist ready for the call.",
      meetingLink: "https://meet.legalconnect.demo/vance-jenkins",
      createdAt: new Date("2026-09-20T14:30:00Z").toISOString(),
    },
    {
      _id: "req_demo_02",
      clientId: "usr_client_02",
      clientName: "Michael Chen",
      clientEmail: "michael@demo.legalconnect.com",
      clientPhone: "+1 (555) 021-1002",
      lawyerId: "prof_lawyer_02",
      lawyerName: "Adv. Elena Rostova",
      category: "Corporate & Business Law",
      problemDescription: "Founding a Delaware C-Corp for a fintech product. Need advisory on founder vesting schedules and seed SAFE term review.",
      preferredDate: "2026-09-29",
      preferredTime: "02:00 PM",
      mode: "Video Call",
      status: "Pending",
      notes: "Looking forward to discussing the capitalization structure.",
      createdAt: new Date("2026-09-21T09:15:00Z").toISOString(),
    },
    {
      _id: "req_demo_03",
      clientId: "usr_client_03",
      clientName: "Emily Rodriguez",
      clientEmail: "emily@demo.legalconnect.com",
      clientPhone: "+1 (555) 021-1003",
      lawyerId: "prof_lawyer_03",
      lawyerName: "Adv. Priya Patel",
      category: "Divorce & Family Law",
      problemDescription: "Seeking legal guidance on mutual consent separation and equitable division of joint property in Illinois.",
      preferredDate: "2026-09-30",
      preferredTime: "10:30 AM",
      mode: "Phone Call",
      status: "Pending",
      createdAt: new Date("2026-09-21T16:45:00Z").toISOString(),
    },
    {
      _id: "req_demo_04",
      clientId: "usr_client_01",
      clientName: "Sarah Jenkins",
      clientEmail: "sarah@demo.legalconnect.com",
      clientPhone: "+1 (555) 021-1001",
      lawyerId: "prof_lawyer_05",
      lawyerName: "Adv. Aisha Morales",
      category: "Employment & Labour Law",
      problemDescription: "Inquiry regarding sudden severance agreement with non-compete clause spanning the entire state.",
      preferredDate: "2026-09-15",
      preferredTime: "03:00 PM",
      mode: "Video Call",
      status: "Completed",
      notes: "Initial consultation completed. Client advised to review non-compete reasonableness.",
      createdAt: new Date("2026-09-12T11:00:00Z").toISOString(),
    },
  ];

  // 5. Initial Demo Cases
  const demoCases: ICase[] = [
    {
      _id: "case_demo_01",
      clientId: "usr_client_01",
      clientName: "Sarah Jenkins",
      lawyerId: "prof_lawyer_01",
      lawyerName: "Adv. Marcus Vance",
      title: "Jenkins v. Hudson Properties - Deposit Recovery",
      category: "Property Law",
      description: "Recovery of wrongful security deposit deduction and statutory interest under state residential tenancy statutes.",
      status: "Active",
      nextAction: "Draft formal 10-day demand letter with inspection photos",
      notes: "Client provided move-in checklist with explicit timestamps.",
      timeline: [
        {
          id: "tl_1",
          title: "Consultation Requested",
          description: "Sarah submitted dispute details regarding withheld deposit.",
          date: "2026-09-20",
          completed: true,
        },
        {
          id: "tl_2",
          title: "Lawyer Accepted",
          description: "Adv. Marcus Vance confirmed consultation & created active case file.",
          date: "2026-09-20",
          completed: true,
        },
        {
          id: "tl_3",
          title: "Documents Submitted",
          description: "Lease agreement and move-in inspection report uploaded.",
          date: "2026-09-21",
          completed: true,
        },
        {
          id: "tl_4",
          title: "Consultation Completed",
          description: "Reviewed evidence and confirmed statutory violation basis.",
          date: "2026-09-22",
          completed: true,
        },
        {
          id: "tl_5",
          title: "Case Active - Formal Demand",
          description: "Drafting formal statutory demand letter.",
          date: "2026-09-23",
          completed: false,
        },
        {
          id: "tl_6",
          title: "Case Closed",
          description: "Resolution reached and escrow funds reimbursed.",
          date: "Pending",
          completed: false,
        },
      ],
      createdAt: new Date("2026-09-20T15:00:00Z").toISOString(),
      updatedAt: new Date("2026-09-22T10:00:00Z").toISOString(),
    },
  ];

  // 6. Demo Documents
  const demoDocuments: IDocument[] = [
    {
      _id: "doc_demo_01",
      caseId: "case_demo_01",
      clientId: "usr_client_01",
      clientName: "Sarah Jenkins",
      lawyerId: "prof_lawyer_01",
      fileName: "Residential_Lease_Agreement_Hudson_2025.pdf",
      fileType: "Agreement",
      fileSize: "1.4 MB",
      fileUrl: "#demo-file",
      uploadedBy: "client",
      createdAt: new Date("2026-09-21T10:00:00Z").toISOString(),
    },
    {
      _id: "doc_demo_02",
      caseId: "case_demo_01",
      clientId: "usr_client_01",
      clientName: "Sarah Jenkins",
      lawyerId: "prof_lawyer_01",
      fileName: "MoveIn_MoveOut_Inspection_Log.pdf",
      fileType: "Notice",
      fileSize: "840 KB",
      fileUrl: "#demo-file",
      uploadedBy: "client",
      createdAt: new Date("2026-09-21T10:05:00Z").toISOString(),
    },
    {
      _id: "doc_demo_03",
      caseId: "case_demo_01",
      clientId: "usr_client_01",
      clientName: "Sarah Jenkins",
      lawyerId: "prof_lawyer_01",
      fileName: "Statutory_Demand_Draft_v1.docx",
      fileType: "Court document",
      fileSize: "220 KB",
      fileUrl: "#demo-file",
      uploadedBy: "lawyer",
      createdAt: new Date("2026-09-22T08:30:00Z").toISOString(),
    },
  ];

  const allUsers = [adminUser, ...clientUsers, ...lawyerUsers];

  dbStore.resetData({
    users: allUsers,
    lawyerProfiles,
    consultationRequests: demoConsultations,
    cases: demoCases,
    documents: demoDocuments,
    classifications: [],
  });

  console.log("Database seeded successfully with 20 lawyers, 5 clients, 1 admin, consultations, cases, and documents.");
}
